RESOURCE_MAP = {
    "HTML": ["freeCodeCamp Responsive Web Design", "Traversy Media HTML Crash Course"],
    "CSS": ["freeCodeCamp CSS Course", "Kevin Powell CSS Tutorials"],
    "JavaScript": ["freeCodeCamp JavaScript Algorithms", "Net Ninja JavaScript Playlist"],
    "Git": ["freeCodeCamp Git and GitHub", "GitHub Crash Course - Traversy Media"],
    "React": ["Scrimba Learn React", "Net Ninja React Tutorial"],
    "Bootstrap": ["Bootstrap Tutorial - freeCodeCamp", "Bootstrap Crash Course - Traversy Media"],
    "Node.js": ["Node.js Full Course - freeCodeCamp", "Net Ninja Node.js Tutorial"],
    "Responsive Design": ["Responsive Web Design - freeCodeCamp"],
    "TypeScript": ["TypeScript Course - freeCodeCamp"],
    "Next.js": ["Next.js Tutorial - freeCodeCamp"],
    "Web Performance": ["Web Performance Full Guide - YouTube"],
    "API Integration": ["REST API Tutorial - freeCodeCamp"],

    "Python": ["Python for Everybody - freeCodeCamp", "Corey Schafer Python Tutorials"],
    "Pandas": ["Pandas Tutorial - Keith Galli", "Data School Pandas Playlist"],
    "Statistics": ["Statistics Full Course - Khan Academy", "Statistics for Data Science - YouTube"],
    "SQL": ["SQL Full Course - freeCodeCamp", "Tech With Tim SQL Tutorial"],
    "Machine Learning": ["Machine Learning Course - freeCodeCamp", "Andrew Ng ML Specialization"],
    "Data Visualization": ["Data Visualization with Python - freeCodeCamp"],
    "NumPy": ["NumPy Tutorial - freeCodeCamp"],
    "Scikit-learn": ["Scikit-learn Tutorial - YouTube"],
    "Deep Learning": ["Deep Learning Course - freeCodeCamp"],
    "Model Tuning": ["Hyperparameter Tuning - YouTube"],
    "Feature Engineering": ["Feature Engineering Course - YouTube"],
    "Deployment": ["ML Model Deployment - YouTube"],

    "Linux": ["Linux for Beginners - freeCodeCamp"],
    "Networking": ["Computer Networking Course - freeCodeCamp"],
    "Cloud Basics": ["Cloud Computing Full Course - YouTube"],
    "AWS": ["AWS Course - freeCodeCamp"],
    "Docker": ["Docker Full Course - freeCodeCamp"],
    "CI/CD": ["CI/CD Pipeline Tutorial - YouTube"],
    "Shell Scripting": ["Shell Scripting Tutorial - YouTube"],
    "Kubernetes": ["Kubernetes Course - freeCodeCamp"],
    "Terraform": ["Terraform Full Course - YouTube"],
    "Monitoring": ["DevOps Monitoring Tutorial - YouTube"],
    "Cloud Security": ["Cloud Security Basics - YouTube"],

    "Java": ["Java Full Course - freeCodeCamp"],
    "Kotlin": ["Kotlin for Beginners - YouTube"],
    "Flutter": ["Flutter Course - freeCodeCamp"],
    "UI Design": ["UI/UX Design Basics - YouTube"],
    "Firebase": ["Firebase Tutorial - freeCodeCamp"],
    "State Management": ["Flutter State Management - YouTube"],
    "SQLite": ["SQLite Tutorial - YouTube"],
    "Performance Optimization": ["Performance Optimization Guide - YouTube"],
    "Push Notifications": ["Push Notification Tutorial - YouTube"],
    "Testing": ["Software Testing Tutorial - YouTube"],

    "Excel": ["Excel for Beginners - freeCodeCamp", "Kevin Stratvert Excel Tutorial"],
    "Data Cleaning": ["Data Cleaning with Python - YouTube"],
    "Power BI": ["Power BI Full Course - freeCodeCamp", "Power BI Tutorial - Simplilearn"],
    "Tableau": ["Tableau Tutorial - freeCodeCamp"],
    "Dashboard Design": ["Dashboard Design Principles - YouTube"],
    "Business Insights": ["Business Analytics Tutorial - YouTube"],
    "Forecasting": ["Forecasting in Analytics - YouTube"],
    "Automation": ["Automation with Python - YouTube"],

    "Express.js": ["Express.js Tutorial - freeCodeCamp"],
    "MongoDB": ["MongoDB Course - freeCodeCamp"],
    "Authentication": ["Authentication Tutorial - YouTube"],
    "System Design": ["System Design Basics - YouTube"],
    "API Security": ["API Security Tutorial - YouTube"],

    "APIs": ["API Basics - freeCodeCamp"],
    "Django": ["Django Full Course - freeCodeCamp"],
    "Flask": ["Flask Tutorial - freeCodeCamp"],
    "Database Design": ["Database Design Course - YouTube"],
    "Caching": ["Caching Explained - YouTube"],
    "Scalability": ["Scalable Systems Design - YouTube"],
    "Microservices": ["Microservices Tutorial - YouTube"],

    "UI/UX": ["UI UX Design Course - freeCodeCamp"],
    "API Handling": ["API Fetch Tutorial - YouTube"],
    "Accessibility": ["Web Accessibility Tutorial - freeCodeCamp"],

    "Model Evaluation": ["Model Evaluation in ML - YouTube"],
    "MLOps": ["MLOps Full Course - YouTube"],
    "TensorFlow": ["TensorFlow Course - freeCodeCamp"],

    "Communication": ["Communication Skills Course - Great Learning"],
    "Business Analysis": ["Business Analysis Fundamentals - Simplilearn"],
    "Requirements Gathering": ["Requirements Gathering Tutorial - YouTube"],
    "Data Modeling": ["Data Modeling Tutorial - Lucidchart"],
    "Stakeholder Management": ["Stakeholder Management Basics - YouTube"],
    "Process Optimization": ["Business Process Improvement - YouTube"],

    "Testing Basics": ["Software Testing Basics - YouTube"],
    "Bug Reporting": ["Bug Reporting Tutorial - YouTube"],
    "Manual Testing": ["Manual Testing Full Course - YouTube"],
    "Selenium": ["Selenium Full Course - freeCodeCamp"],
    "Test Cases": ["How to Write Test Cases - YouTube"],
    "API Testing": ["Postman API Testing - YouTube"],
    "Performance Testing": ["Performance Testing Tutorial - YouTube"],
    "Security Testing": ["Security Testing Basics - YouTube"],
    "CI/CD Testing": ["CI CD Testing Tutorial - YouTube"],
    "Framework Design": ["Test Automation Framework Design - YouTube"],

    "DBMS": ["DBMS Full Course - YouTube"],
    "Backup Recovery": ["Database Backup and Recovery - YouTube"],
    "MySQL": ["MySQL Full Course - freeCodeCamp"],
    "PostgreSQL": ["PostgreSQL Tutorial - freeCodeCamp"],
    "Performance Tuning": ["SQL Performance Tuning - YouTube"],
    "Security": ["Database Security Basics - YouTube"],
    "Replication": ["Database Replication Tutorial - YouTube"],
    "High Availability": ["High Availability Systems - YouTube"],
    "Optimization": ["Database Optimization - YouTube"],
    "Cloud Databases": ["Cloud Databases Tutorial - YouTube"],

    "Networking Basics": ["Networking Basics - freeCodeCamp"],
    "IP Addressing": ["IP Addressing Tutorial - YouTube"],
    "Routing": ["Routing and Switching - YouTube"],
    "Switching": ["Switching Concepts - YouTube"],
    "Cisco": ["Cisco Networking Course - YouTube"],
    "Network Security": ["Network Security Basics - YouTube"],
    "Firewall": ["Firewall Tutorial - YouTube"],
    "Troubleshooting": ["Network Troubleshooting Guide - YouTube"],
    "Cloud Networking": ["Cloud Networking Course - YouTube"],
    "Infrastructure Design": ["Network Design Basics - YouTube"],

    "Security Basics": ["Cyber Security Full Course - freeCodeCamp"],
    "Threat Awareness": ["Cyber Threat Awareness - YouTube"],
    "Ethical Hacking": ["Ethical Hacking Course - freeCodeCamp"],
    "SIEM": ["SIEM Tutorial - YouTube"],
    "Incident Response": ["Incident Response Basics - YouTube"],
    "Vulnerability Assessment": ["Vulnerability Assessment Tutorial - YouTube"],
    "Penetration Testing": ["Penetration Testing Course - YouTube"],
    "Malware Analysis": ["Malware Analysis Basics - YouTube"],
    "Digital Forensics": ["Digital Forensics Course - YouTube"]
}

def get_resources(missing_skills):
    recommendations = []
    for skill in missing_skills:
        if skill in RESOURCE_MAP:
            recommendations.append({
                "skill": skill,
                "resources": RESOURCE_MAP[skill]
            })
    return recommendations